### ISSUE TITLE
Can't roundtrip fixed shape tensors to Lance

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1170]
We can write them, but it seems we aren't storing the schema metadata correctly because we an error when trying to load the schema:

```
pyarrow.lib.ArrowInvalid: Invalid serialized JSON data: 
```

**Comment by wjones127** [comment]
Reproduction:

```python
import pyarrow as pa
import lance


tensor_type = pa.fixed_shape_tensor(pa.float32(), [2, 3])
inner = pa.array([float(x) for x in range(1, 7)], pa.float32())
storage = pa.FixedSizeListArray.from_arrays(inner, 6)
f32_array = pa.ExtensionArray.from_storage(tensor_type, storage)

tab = pa.table({'x': f32_array})

dataset = lance.write_dataset(tab, "test_dataset")
```

```
>>> dataset.schema()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willjones/Documents/lance/python/python/lance/dataset.py", line 199, in schema
    return self._ds.schema
  File "pyarrow/types.pxi", line 3054, in pyarrow.lib.Schema._import_from_c
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Invalid serialized JSON data:
```

```
>>> dataset.to_table()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willjones/Documents/lance/python/python/lance/dataset.py", line 269, in to_table
    ).to_table()
  File "/Users/willjones/Documents/lance/python/python/lance/dataset.py", line 871, in to_table
    return self.to_reader().read_all()
  File "/Users/willjones/Documents/lance/python/python/lance/dataset.py", line 874, in to_reader
ExecNode(Projection): channel closed
    return self._scanner.to_pyarrow()
  File "pyarrow/ipc.pxi", line 806, in pyarrow.lib.RecordBatchReader._import_from_c
ExecNode(Projection): channel closed
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Invalid serialized JSON data: 
```

**Comment by wjones127** [comment]
Fixed by https://github.com/lancedb/lance/pull/1173
