### ISSUE TITLE
[Bug] Lance dataset writes crashes with non-string bytes in the schema metadata

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1178]
To reproduce

```python

def test_schema_with_bytes_metadata(tmp_path: Path):
    schema = pa.schema(
        [pa.field("a", pa.float64())], metadata={"key": pickle.dumps("value")}
    )
    data = pa.table({"a": [1.0, 2.0]}).to_batches()
    dataset = lance.write_dataset(data, tmp_path, schema=schema)
    assert dataset.schema == schema
```

Running with `RUST_BACKTRACE=1` got the following stack trace

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("invalid utf-8 sequence of 1 bytes from index 0")', /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-43.0.0/src/ffi_stream.rs:273:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: arrow::ffi_stream::get_stream_schema
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-43.0.0/src/ffi_stream.rs:273:22
   5: arrow::ffi_stream::ArrowArrayStreamReader::try_new
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-43.0.0/src/ffi_stream.rs:293:22
   6: <arrow::ffi_stream::ArrowArrayStreamReader as arrow::pyarrow::FromPyArrow>::from_pyarrow
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-43.0.0/src/pyarrow.rs:273:29
   7: lance::dataset::write_dataset::{{closure}}
             at ./src/dataset.rs:573:27
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/park.rs:283:63
   9: tokio::runtime::coop::with_budget
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/coop.rs:107:5
  10: tokio::runtime::coop::budget
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/coop.rs:73:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/park.rs:283:31
  12: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/context.rs:315:13
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/scheduler/multi_thread/mod.rs:66:9
  14: tokio::runtime::runtime::Runtime::block_on
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/runtime.rs:304:45
  15: lance::dataset::write_dataset
             at ./src/dataset.rs:560:5
  16: lance::dataset::_::__pyfunction_write_dataset
             at ./src/dataset.rs:557:1
  17: pyo3::impl_::trampoline::cfunction_with_keywords::{{closure}}
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.1/src/impl_/trampoline.rs:41:35
  18: pyo3::impl_::trampoline::trampoline_inner::{{closure}}
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.1/src/impl_/trampoline.rs:181:54
  19: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  20: ___rust_try
  21: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  22: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  23: pyo3::impl_::trampoline::trampoline_inner
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.1/src/impl_/trampoline.rs:181:9
  24: pyo3::impl_::trampoline::cfunction_with_keywords
             at /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.1/src/impl_/trampoline.rs:41:13
  25: lance::dataset::_::<impl lance::dataset::write_dataset::MakeDef>::DEF::trampoline
             at ./src/dataset.rs:557:1
  26: _cfunction_call
  27: __PyObject_MakeTpCall
  28: _call_function
  29: __PyEval_EvalFrameDefault
  30: __PyEval_Vector
  31: _call_function
  32: __PyEval_EvalFrameDefault
```

It seems that the upstream arrow-rs ffi_stream assumes the key/value of schema metadata are validated utf8 python strings.

**Comment by changhiskhan** [comment]
Maybe a quick fix to prevent the panic is to just check if the metadata is valid utf8 and if not then raise an exception?

**Comment by wjones127** [comment]
> Maybe a quick fix to prevent the panic is to just check if the metadata is valid utf8 and if not then raise an exception?

Yeah I think we could add that check after converting to a reader 👍

**Comment by changhiskhan** [comment]
do we want to validate before writing or reading?
