### ISSUE TITLE
Panic in `get_sub_vector_centroids`

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#2006]
As reported from Discord:

```
thread 'lance_background_thread' panicked at /home/runner/work/lance/lance/rust/lance/src/utils/tokio.rs:34:24:
called Result::unwrap() on an Err value: RecvError(())
thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq/utils.rs:63:5:
sub_vector idx: 96, num_sub_vectors: 96
Traceback (most recent call last):
  File "/.../lancedb_poc/....py", line 68, in <module>
    result = vector_db.similarity_search("提供有关电动汽车电池的信息")
  File "/.../lancedb_poc/.venv/lib/python3.9/site-packages/langchain_community/vectorstores/lancedb.py", line 128, in similarity_search
    self._connection.search(embedding, vector_column_name=self._vector_key)
  File "/.../lancedb_poc/.venv/lib/python3.9/site-packages/lancedb/query.py", line 500, in to_arrow
    return self._table._execute_query(query)
  File "/.../lancedb_poc/.venv/lib/python3.9/site-packages/lancedb/table.py", line 1456, in _execute_query
    return ds.to_table(
  File "/.../lancedb_poc/.venv/lib/python3.9/site-packages/lance/dataset.py", line 397, in to_table
    return self.scanner(
  File "/.../lancedb_poc/.venv/lib/python3.9/site-packages/lance/dataset.py", line 2051, in to_table
    return self.to_reader().read_all()
  File "pyarrow/ipc.pxi", line 757, in pyarrow.lib.RecordBatchReader.read_all
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
OSError: Io error: Execution error: External error: Execution error: ExecNode(Take): thread panicked: task 34 panicked
```

The search is happening on lancedb version 5.7 but the index was trained on lancedb version 5.3

**Comment by westonpace** [comment]
Dropping the `num_sub_vectors` to 48 and recreating the index worked around the issue in the meantime.
