### ISSUE TITLE
type mismatch and pop error like `should have type null but type was string`

### ISSUE THREAD

**Issue by zeddit** [lancedb/lance#2199]
I have a pandas dataframe but cannot be stored into lance.

the version of `pylance` is 0.10.12

the error looks like below:
```
        date market        sym  name     fee    size  term  prevclose  mcap
0 2023-04-07     深A  000001.SZ  平安银行  0.0488   24600    10        NaN   NaN
1 2023-04-07     深A  000001.SZ  平安银行  0.0488    4800    28        NaN   NaN
2 2023-04-07     深A  000002.SZ   万科A  0.0488   29100    17        NaN   NaN
3 2023-04-07     深A  000002.SZ   万科A  0.0488  324300    28        NaN   NaN
4 2023-04-07     深A  000009.SZ  中国宝安  0.0488  118800     6        NaN   NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       3095 non-null   datetime64[ns]
 1   market     3095 non-null   object
 2   sym        3095 non-null   object
 3   name       3095 non-null   object
 4   fee        3095 non-null   float64
 5   size       3095 non-null   int64
 6   term       3095 non-null   int64
 7   prevclose  0 non-null      float64
 8   mcap       0 non-null      float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(3)
memory usage: 217.7+ KB
None
date: timestamp[ns]
market: string
sym: string
name: string
fee: double
size: int64
term: int64
prevclose: double
mcap: double
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 1250
Traceback (most recent call last):
  File "/home/zeddit/aqdatac-sbl/tests/gtja_ingest.py", line 200, in <module>
    process_sheet_realtime(excel_file, date)
  File "/home/zeddit/aqdatac-sbl/tests/gtja_ingest.py", line 69, in process_sheet_realtime
    lance.write_dataset(df, "s3://lance-aqdatac/gtja_sbl_securities_list_realtime",
  File "/home/zeddit/miniconda3/envs/lance/lib/python3.10/site-packages/lance/dataset.py", line 2404, in write_dataset
    inner_ds = _write_dataset(reader, uri, params)
OSError: Append with different schema: `market` should have type null but type was string, `sym` should have type null but type was string, `name` should have type null but type was string, `fee` should have type null but type was double, `size` should have type null but type was int64, `term` should have type null but type was int64, `prevclose` should have type null but type was double, `mcap` should have type null but type was double, location: /home/runner/work/lance/lance/rust/lance-core/src/datatypes/schema.rs:150:27
```

**Comment by zeddit** [comment]
the root cause is a previous dataset with different schema remains in the storage.
