### ISSUE TITLE
FTS search error on empty table: `panicked with message "assertion `left == right` failed`

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#3013]
If I create an FTS index on an empty table and then search, get a panic:

```python
import lance
import pyarrow as pa

assert lance.__version__ == '0.18.2'

data = pa.table({'text': pa.array([], type=pa.string())})
ds = lance.write_dataset(data, 'test', mode='overwrite')

ds.create_scalar_index('text', 'INVERTED')

ds.to_table(full_text_query="banana")
```

```
thread 'lance_background_thread' panicked at /Users/runner/work/lance/lance/rust/lance-index/src/scalar/lance_format.rs:177:9:
assertion `left == right` failed
  left: 0
 right: 1
thread 'lance_background_thread' panicked at /Users/runner/work/lance/lance/rust/lance-index/src/scalar/lance_format.rs:177:9:
assertion `left == right` failed
  left: 0
 right: 1
```

**Comment by wjones127** [comment]
We get the same error if the strings are all empty:

```python
import lance
import pyarrow as pa

assert lance.__version__ == '0.18.2'

data = pa.table({'text': ['', ''] })
ds = lance.write_dataset(data, 'test', mode='overwrite')
ds.create_scalar_index('text', 'INVERTED')
ds.optimize.optimize_indices()
```

```
OSError: LanceError(IO): task 5118 panicked with message "assertion `left == right` failed\n  left: 0\n right: 1", /Users/runner/work/lance/lance/rust/lance-index/src/scalar/inverted/index.rs:268:22
```

Also, a user reported a slightly different error when doing something similar in LanceDB [^1].

```python
table = db.create_table(
    "test_fts_table",
    data=[
        {"vector": [3.1, 4.1], "id": "1", "text": ""},
    ],
)
table.create_fts_index("text", use_tantivy=False, replace=True)
table.to_lance().optimize.optimize_indices()
```

```
OSError: Invalid user input: Cannot read empty range 0..0 from file
```

[^1]: https://discord.com/channels/1030247538198061086/1197630499926057021/1296951700107825246
