### ISSUE TITLE
2.1 miniblock + bitpacking does not support chunks of all-zero data

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#3102]
The bit width is zero and we get:

```
thread 'lance-cpu' panicked at rust/lance-encoding/src/compression_algo/fastlanes.rs:626:18:
internal error: entered unreachable code: Unsupported width: 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: <u32 as lance_encoding::compression_algo::fastlanes::BitPacking>::unchecked_pack
             at ./src/compression_algo/fastlanes.rs:626:18
   3: lance_encoding::encodings::physical::bitpack_fastlanes::BitpackMiniBlockEncoder::chunk_data
             at ./src/encodings/physical/bitpack_fastlanes.rs:1612:17
   4: <lance_encoding::encodings::physical::bitpack_fastlanes::BitpackMiniBlockEncoder as lance_encoding::encoder::MiniBlockCompressor>::compress
             at ./src/encodings/physical/bitpack_fastlanes.rs:1687:54
   5: lance_encoding::encodings::logical::primitive::PrimitiveStructuralEncoder::encode_miniblock
             at ./src/encodings/logical/primitive.rs:1759:49
   6: lance_encoding::encodings::logical::primitive::PrimitiveStructuralEncoder::do_flush::{{closure}}
             at ./src/encodings/logical/primitive.rs:1826:21
```

**Comment by Xuanwo** [comment]
I think we can just use RLE in this case.

**Comment by Xuanwo** [comment]
Let's try support all ZERO for bitpacking.
