### ISSUE TITLE
Missing dependency tqdm

### ISSUE THREAD

**Issue by hongbo-miao** [lancedb/lance#3305]
# Issue

My pyproject.toml using uv:

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "pylance==0.21.0",
]
```

Currently calling

```py
from lance.vector import vec_to_table
```

will cause error:

```py
python src/main.py
Traceback (most recent call last):
  File "/Users/hongbo-miao/Clouds/Git/hongbomiao.com/data-storage/lance/src/main.py", line 6, in <module>
    from lance.vector import vec_to_table
  File "/Users/hongbo-miao/Clouds/Git/hongbomiao.com/data-storage/lance/.venv/lib/python3.12/site-packages/lance/vector.py", line 13, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

# Workaround solution

Manually include `tqdm`

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "pylance==0.21.0",
  "tqdm==4.67.1",
]
```

**Comment by wjones127** [comment]
Thanks for reporting this. I think it's intentional that `tqdm` is not a required dependency. We only use it in a few helper modules. But it is confusing that some modules import it, and you get a plain import error. I think other libraries would give an error saying something like "lance.vector requires tqdm". So we could add a better error message.

Alternatively, it might be even nicer if we just made tqdm entirely optional. We have some functions here for checking if a package is installed cheaply: https://github.com/lancedb/lance/blob/main/python/python/lance/dependencies.py Perhaps if `tqdm` isn't installed we define a no-op `tqdm()` stub that can be used instead.

**Comment by Xuanwo** [comment]
Closing as completed. `tqdm` is now a declared Python project dependency.
