### ISSUE TITLE
Bug: PlainDecoder: request([0..1025]) out of range: [0..1024] on Oxford Pet dataset

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#536]
Reproduce 

```
>>> import lance
>>> dataset = lance.dataset("s3://eto-public/datasets/oxford_pet/oxford_pet.lance")
>>> t = dataset.to_table()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lei/work/lance/python/python/lance/dataset.py", line 123, in to_table
    ).to_table()
  File "/Users/lei/work/lance/python/python/lance/dataset.py", line 418, in to_table
    return self.to_reader().read_all()
  File "pyarrow/ipc.pxi", line 750, in pyarrow.lib.RecordBatchReader.read_all
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: C Data interface error: Io error: PlainDecoder: request([0..1025]) out of range: [0..1024]
>>> Failed to scan data: channel closed
```

**Comment by eddyxu** [comment]
Action item: regenerate oxford_pet dataset.
